### ISSUE TITLE
Word RegExp fails to match valid words and closes dialog

### ISSUE THREAD

**Issue by whitlockjc** [atom/autocomplete#13]
Whenever I use autocomplete in CSS mode, any time I type the hyphen in a CSS property name, the whole dialog disappears.  So if I type in `font`, it shows all of the CSS properties starting with **font** but as soon as I type the `-` after `font` to find things like `font-family`, `font-size`, etc., the dialog disappears.  I checked the developer tools and there were no errors.

This is my first bug/feature request for Atom.io so if I missed something in the guidelines, let me know.  I did search to see if anyone had reported this and didn't see anything.  Also, if I can provide more details or help with the fix, let me know.

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
