### ISSUE TITLE
Canceling autocomplete with ESC will also turns off vim insert mode.

### ISSUE THREAD

**Issue by ojosdegris** [atom/autocomplete#14]
Can we make it keep vim insert mode on when autocomplete overlay is cancelled with ESC?

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
