### ISSUE TITLE
Interferes with closing select list when bound to `escape`

### ISSUE THREAD

**Issue by nathansobo** [atom/autocomplete#16]
Some have mapped autocomplete to `escape` to match TextMate. But this interferes with their ability to close mini editors. We may want to call `abortKeyBinding` in the event the autocompleter has no suggestions.

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
