### ISSUE TITLE
When there are no matches

### ISSUE THREAD

**Issue by no2665** [atom/autocomplete#17]
If you type something in, and there are no autocomplete matches, pressing enter makes what you've typed in disappear. It might be quite nice if what you've typed gets put in even if there are no matches. 

For instance, sometimes I use autocomplete just to see if a variable name exists already, and if it doesn't then I use that name, but pressing enter makes what I've typed vanish, and then I have to type the name in again, which is a waste of time.

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
