### ISSUE TITLE
Feature request: Context-aware hints

### ISSUE THREAD

**Issue by timseverien** [atom/autocomplete#22]
One of my favourite features in all IDE's from JetBrains is it's hinting and auto-completion. I call it context-aware hinting.

When you're writing HTML and you're about to add a class to an element, it lists all known classnames defined anywhere else in your project. In PHP, when you've created an instance of class X and want to call a function, it lists all known methods of just that class. It looks at where your cursor is, identifies the syntax before it and lists only relevant information.

![PHPStorm](http://i.imgur.com/eIyp94E.png)
![Atom](http://i.imgur.com/I6z0rXM.png)

PHP classes seem to work OK, could be improved a little. However, I'd like to see this extended over other languages as well like the HTML-CSS example I mentioned.

So, can we have this?

**Comment by ilpaijin** [comment]
Same here, I've already switched to Atom (kind of trial period...) and I'm waiting for this feature too!

**Comment by maynull** [comment]
Is there any news on this one ?

**Comment by Henje** [comment]
I think the main progress on this topic is concentrated in this issue: atom/atom#4364

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
