### ISSUE TITLE
Ability to make autocomplete case sensitive

### ISSUE THREAD

**Issue by peterbe** [atom/autocomplete#36]
Perhaps this feature request already exists, but I can't find it. 

I'd love if it possible to change my autocomplete to become case sensitive. Probably something that's pref'ed off by default. 

When I type "Fo" and there is "foobar" and "Foodmixer" in the buffer I only want it to autocomplete suggest "Foodmixer".

**Comment by peterjeliot** [comment]
I also want this feature. Case-insensitive autocomplete finds too many things.

**Comment by jeromeetienne** [comment]
+1 while coding, we must have options to controls what is display.

- "case ignore" boolean
- i can think about another... "force start with" boolean

**Comment by janmarek** [comment]
+1

**Comment by vemv** [comment]
+1

Fix is simple though: https://github.com/vemv/autocomplete/commit/cd69195f1f4666903e030ae35fac64d90aad9432

For the moment I'll be using my forked package, but I must say case-insensitive fuzzy completion is objectively bad.

**Comment by siannopollo** [comment]
I'll also give my +1 for allowing case-sensitive autocomplete, at least as an option. Too many times I'll try to autocomplete a certain word, only to find that its titleized version (which is also in the file) takes precedence over the word I really want.

Example: 
![giphy](https://cloud.githubusercontent.com/assets/5378/6972277/9da38ad8-d950-11e4-9019-af71be053032.gif)

**Comment by mjrk** [comment]
+1

For the moment, the `Use Strict Matching For Built-In Provider`-option helped.

**Comment by peterbe** [comment]
@mjrk What is that? How do you enable that?

**Comment by mnquintana** [comment]
This repo is no longer maintained - Atom's autocomplete functionality is now provided by https://github.com/atom/autocomplete-plus

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.

**Comment by peterbe** [comment]
Here's the [same issue on the autocomplete-plus](https://github.com/atom/autocomplete-plus/issues/42) package.
