### ISSUE TITLE
Feature request: Pneumonic matching a la ST3

### ISSUE THREAD

**Issue by focusaurus** [atom/autocomplete#37]
In Sublime Text, you can autocomplete by an in-order pneumonic or any sequence of characters. For example, I can type `gln<tab>` and have `getLastName` as a possible completion. I am addicted to this and consider it a killer feature of ST. Would love to see it available in this package for atom.

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
