### ISSUE TITLE
Unexpected autocompleting in C++ code

### ISSUE THREAD

**Issue by Grelek** [atom/autocomplete#38]
Atom on Windows 8.1

Simply open a new C++ file and start typing `#include <iostream` and when you'll write the `>` character, Atom will autocomplete [this](http://pastebin.com/iG4kkLmv).

I think this absolutely isn't feature, it's a bug.

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
