### ISSUE TITLE
Feature Request: ignore words in comments

### ISSUE THREAD

**Issue by federeghe** [atom/autocomplete#44]
Autocomplete words that are previously typed in comments it's not very useful :)

e.g.
```
/**
  * this is a comment
  */
```
if I type "co" and autocomplete, it should no propose "comment" (make this configurable would be great!)

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
