### ISSUE TITLE
Inconsistent autocompletion

### ISSUE THREAD

**Issue by ignism** [atom/autocomplete#45]
Autocomplete is not reliable for me. Tried it on a fresh install but it sometimes does not give me any suggestions at all. I posted it on the forums too:
https://discuss.atom.io/t/autocomplete-doesnt-work-everytime/11962

**Comment by izuzak** [comment]
@ignism After reading the discuss thread you linked to, it seems that you were able to figure out why you were seeing inconsistent results. If that's not the case -- let us know and please provide a specific example.
