### ISSUE TITLE
the keymap of "autocomplete:toggle"

### ISSUE THREAD

**Issue by HarvinWang** [atom/autocomplete#48]
In my country , the Keystroke of "ctrl-space" is always regarded as the operation of switchover   input method. So I think that using  "ctrl-alt" or "alt-enter" as default just like the eclipse ,will be better. Thanks.

**Comment by izuzak** [comment]
@HarvinWang You should be able to modify the keybinding in your keymap file:

https://atom.io/docs/latest/customizing-atom#customizing-key-bindings

Also, `ctrl+space` is used to trigger autocomplete in other editors as well, such as Sublime Text.

**Comment by basarat** [comment]
> autocomplete in other editors as well, such as Sublime Text.

and visual studio / Webstorm ( also intellij / phpstorm / pycharm / rubymine )
