### ISSUE TITLE
Autocomplete only works on last selection if multiple insertion points are active

### ISSUE THREAD

**Issue by impinball** [atom/autocomplete#49]
**Platform:** Ubuntu GNOME 14.04, 64-bit

### Basic steps to repro

1. Create multiple insertion points (e.g. ctrl-click)
2. Attempt to tab-complete a word
3. Only the last insertion point made will have the snippet, and that snippet will not overwrite the prefix of that last occurence.

### Expected behavior

All insertion points will autocomplete with the word, as would normally happen with a single insertion point. Different words aren't necessecarily expected to autocomplete.

### Observed behavior

(vertical bar == insertion point)

Known word: `MyClass`
```
MyC|
MyC|
MyC|
```

Expands to:
```
MyC
MyC
MyCMyClass|
```

---

I don't expect this specific case to work:

Known words: `foobar`, `barfoo`
```
foo|
bar|
```

Expands to:
```
foobar|
barfoo|
```

---

I use the multiple insertion point feature somewhat extensively, given it's very high usefulness when refactoring masses of code quickly.

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
