### ISSUE TITLE
When pressing enter, the selected autocomplete not replacing my text

### ISSUE THREAD

**Issue by kokizzu** [atom/autocomplete#55]
before pressing enter (the cursor is on the end of `DEl`)

![image](https://cloud.githubusercontent.com/assets/1061610/5217616/871ba748-7675-11e4-89e5-18cf57105416.png)

pressing enter (the cursor is below `DEl`)

![image](https://cloud.githubusercontent.com/assets/1061610/5217629/a6bc5c6e-7675-11e4-9120-7659c65f5bbe.png)

it should replace my typed text instead of newline

**Comment by izuzak** [comment]
@kokizzu Can you still reproduce this issue in the latest version of Atom (and in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode))? I just tried reproducing an wasn't able to. Also, that doesn't look like the official autocomplete package -- are you perhaps using a different package?
