### ISSUE TITLE
Doesn't work with valid unicode characters in variables

### ISSUE THREAD

**Issue by pbihler** [atom/autocomplete#60]
I don't want to discuss, whether unicode characters in varnames are good or bad. They work. And they should be respected by autocomplete.

Currently this doesn't work:
```js
var gründe = 'foo';
alert(g// if I press ctrl+space here, if suggests only "gr", not "gründe"
```

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
