### ISSUE TITLE
Comment Tags

### ISSUE THREAD

**Issue by Lynxaa** [atom/autocomplete#63]
Make it so that when you open a comment, e.g ```/**``` make it auto-complete it.

e.g
```
	/**
	 * 
	 *
	 *
	 */
```

This type of stuff is very useful in IDE's like Eclipse, Netbeans, etc.
Another suggest would be once this feature is implement allow the user to choose to add stuff like,
@author 
@date <date this file was commented/made
@version
@see
etc.

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
