### ISSUE TITLE
PLIST Additions

### ISSUE THREAD

**Issue by WardsParadox** [atom/autocomplete#67]
Using autocomplete you are able to type key, array, dict and press tab to auto fill the tag in <> and with </>. It would be nice if it did this for more data types, like string, integer, boolean ( <true /> <false />), etc.

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
