### ISSUE TITLE
Always show completions when typing

### ISSUE THREAD

**Issue by saschagehlich** [atom/autocomplete#7]
Is that possible with the current architecture?

**Comment by vimes1984** [comment]
+1 for this feature....

**Comment by thedaniel** [comment]
Autocomplete-plus will at some point in the next few months replace autocomplete in core. There's no need to +1 this anymore, it's accepted and in-progress. 

Here's the 1.0 tracking issue: https://github.com/atom/atom/issues/3684
Here's the tracking issue for "autocomplete next": https://github.com/atom/atom/issues/4364

**Comment by vimes1984** [comment]
Ok sorry. Do you want to shut this thread then?

**Comment by thedaniel** [comment]
@vimes1984 No reason to apologize - but I think I'll lock it now but wait to close it until the functionality makes it into core, that way people will see this issue and not open another.

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.

**Comment by benogle** [comment]
We should :fire: this package
