### ISSUE TITLE
Asynchronous feed to autocompletion list 

### ISSUE THREAD

**Issue by iraasta** [atom/autocomplete#70]
I'd like to write an extension to get autocompletion suggestions from the server (real suggestions based on context and indexed 300 files in StdLib) 
But there is no way to make autocompletion asynchronous. 
Can anything be done about it? (I'm afraid that there is too much indices to fit them in native word list

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
