### ISSUE TITLE
autocomplete does not support unicode chars

### ISSUE THREAD

**Issue by kaskelotti** [atom/autocomplete#73]
The autocomplete plugin does not support unicode chars. For example having the following text

> pros präs ääs

when typing 'pr' and hitting CTRL-Space will give only 'pros' as an option. When typing 'ä' or 'ää' and trying auto-complete, the options are shown as if nothing has been typed.

Can be reproduced at least with å, ä and ö, as well as with any char having "a hat on" i.e. û. 

**EDIT** autocomplete version in use is **0.44.0**

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
