### ISSUE TITLE
The keymap of "autocomplete:next/previouse" ?

### ISSUE THREAD

**Issue by ahmadseleem** [atom/autocomplete#75]
It would be nice to implement these keymaps:
- To get to the next item like using ctrl-n as in OS X and emacs:
"autocomplete:next" 
- The same for the previous item...etc

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.

**Comment by ahmadseleem** [comment]
@kevinsawicki it's no longer an issue with the new package. it works as I wished in this request.
Thanks!
