### ISSUE TITLE
Exact prefix matches should take precedence over fuzzy matches 

### ISSUE THREAD

**Issue by gregplaysguitar** [atom/autocomplete#76]
In a css file, if I type

    div {
        background-r

the first completion offered is background-color, with background-repeat second. I presume this is because autocomplete-css specifies them in that order, but background-repeat should really come first because it exactly matches what I'm typing.

**Comment by 50Wliu** [comment]
Hi @gregplaysguitar, what Atom version is this?

**Comment by gregplaysguitar** [comment]
0.199.0

**Comment by 50Wliu** [comment]
In that case, could you please move this bug to [autocomplete-plus](https://github.com/atom/autocomplete-plus) and close this one?  Thanks.

**Comment by gregplaysguitar** [comment]
Sure.
