### ISSUE TITLE
Display suggestions on type

### ISSUE THREAD

**Issue by joaosaragossa** [atom/autocomplete#78]
There is a way to autocomplete display suggestion on type? (without typing `ctrl + space`)

**Comment by thomasjo** [comment]
This package has been deprecated. Atom now comes with autocomplete-plus bundled by default, which has the desired behavior.

**Comment by joaosaragossa** [comment]
@thomasjo Thank you for your answer. How to setup autocomplete-plus to work?

**Comment by thomasjo** [comment]
It is enabled by default. What problem are you having? Also, what version of Atom are you using?

---
NOTE: I'm going to close this issue since it's not really a valid issue, but we can keep discussing here.

**Comment by joaosaragossa** [comment]
@thomasjo I think is the last since there is no update available.

**Comment by thomasjo** [comment]
What type of file are you editing where you are not seeing the autocomplete feature on?

**Comment by 50Wliu** [comment]
@joaosaragossa could you please specify the actual version?  Sometimes there may be a problem with the update server, etc. where you're stuck with an outdated version so it would be great to verify that you are in fact on a release that has the new autocomplete.  As long as your Atom version if 0.199.0 or greater you should be good.

**Comment by joaosaragossa** [comment]
@thomasjo HTML and CSS files
@50Wliu How can I get the version of my Atom?

**Comment by 50Wliu** [comment]
@joaosaragossa The version number is available from the "Help" menu.

**Comment by joaosaragossa** [comment]
@50Wliu version 0.194.0

**Comment by 50Wliu** [comment]
You're currently 13 releases behind (0.207.0 is the latest), and 0.194.0 doesn't come with autocomplete-plus.  What OS are you on?

**Comment by joaosaragossa** [comment]
@50Wliu Elementary OS (Ubuntu 14.04 derivate)

**Comment by 50Wliu** [comment]
Try installing Atom from the Atom website (https://atom.io/) and see if that works.

**Comment by joaosaragossa** [comment]
@50Wliu there is a way to update Atom from bash?

**Comment by 50Wliu** [comment]
Not yet, unless you want to a) use a PPA (if such things exist in elementary) or b) wget the deb.

**Comment by joaosaragossa** [comment]
Thanks guys, I just download the latest version and solve my issue!
