### ISSUE TITLE
In Plain Text mode completion does not appear to work

### ISSUE THREAD

**Issue by szaydel** [atom/autocomplete#79]
It seems to me that when I have plain text set as type of file, completion does not work. Is this to be expected?

**Comment by thomasjo** [comment]
This package has been deprecated and is no longer bundled with Atom. Did you intend to open this on the [autocomplete-plus](https://github.com/atom/autocomplete-plus) repo?

**Comment by szaydel** [comment]
Good question. I may be using a deprecated package without realizing it. Let's close this, and if that's the case I will install autocomplete-plus and make sure I still have this issue, and if so, will re-open it on the right repo.

Thank you!

**Comment by winstliu** [comment]
> if that's the case I will install autocomplete-plus

You shouldn't need to install anything.  Just make sure you're running the latest version of Atom (currently 1.0.2) and `autocomplete-plus` will already be installed.
