### ISSUE TITLE
Add file path autocompletion.

### ISSUE THREAD

**Issue by Techwraith** [atom/autocomplete#8]
I write a lot of js code with require statements in them. We have files all over the place, and it's hard to remember where everything is. It would be great if I could autocomplete file paths (relative to the current file). What would it take to implement something like this?

For reference, neocomplete in vim does a great job of this: https://github.com/Shougo/neocomplete.vim

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
