### ISSUE TITLE
atom editor autocomplete

### ISSUE THREAD

**Issue by ravichandra90** [atom/autocomplete#80]
i am not getting auto complete suggestions in atom editor, i have installed all packages but still im not getting auto complete

**Comment by winstliu** [comment]
This package is no longer included in Atom.  For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
